export const defaultColors: Color[] = [
  {
    name: "slate",
    background: "#94a3b8",
    insetShadowPrimary: "#64748b",
    insetShadowSecondary: "#e2e8f0",
  },
  {
    name: "gray",
    background: "#9ca3af",
    insetShadowPrimary: "#6b7280",
    insetShadowSecondary: "#e5e7eb",
  },
  {
    name: "zinc",
    background: "#a1a1aa",
    insetShadowPrimary: "#71717a",
    insetShadowSecondary: "#e4e4e7",
  },
  {
    name: "neutral",
    background: "#a3a3a3",
    insetShadowPrimary: "#737373",
    insetShadowSecondary: "#e5e5e5",
  },
  {
    name: "stone",
    background: "#a8a29e",
    insetShadowPrimary: "#78716c",
    insetShadowSecondary: "#e7e5e4",
  },
  {
    name: "red",
    background: "#f87171",
    insetShadowPrimary: "#ef4444",
    insetShadowSecondary: "#fecaca",
  },
  {
    name: "orange",
    background: "#fb923c",
    insetShadowPrimary: "#f97316",
    insetShadowSecondary: "#fed7aa",
  },
  {
    name: "amber",
    background: "#fbbf24",
    insetShadowPrimary: "#f59e0b",
    insetShadowSecondary: "#fde68a",
  },
  {
    name: "yellow",
    background: "#facc15",
    insetShadowPrimary: "#eab308",
    insetShadowSecondary: "#fef08a",
  },
  {
    name: "lime",
    background: "#a3e635",
    insetShadowPrimary: "#84cc16",
    insetShadowSecondary: "#d9f99d",
  },
  {
    name: "green",
    background: "#4ade80",
    insetShadowPrimary: "#22c55e",
    insetShadowSecondary: "#bbf7d0",
  },
  {
    name: "emerald",
    background: "#34d399",
    insetShadowPrimary: "#10b981",
    insetShadowSecondary: "#a7f3d0",
  },
  {
    name: "teal",
    background: "#2dd4bf",
    insetShadowPrimary: "#14b8a6",
    insetShadowSecondary: "#99f6e4",
  },
  {
    name: "cyan",
    background: "#22d3ee",
    insetShadowPrimary: "#06b6d4",
    insetShadowSecondary: "#a5f3fc",
  },
  {
    name: "sky",
    background: "#38bdf8",
    insetShadowPrimary: "#0ea5e9",
    insetShadowSecondary: "#bae6fd",
  },
  {
    name: "blue",
    background: "#60a5fa",
    insetShadowPrimary: "#3b82f6",
    insetShadowSecondary: "#bfdbfe",
  },
  {
    name: "indigo",
    background: "#818cf8",
    insetShadowPrimary: "#6366f1",
    insetShadowSecondary: "#c7d2fe",
  },
  {
    name: "violet",
    background: "#a78bfa",
    insetShadowPrimary: "#8b5cf6",
    insetShadowSecondary: "#ddd6fe",
  },
  {
    name: "purple",
    background: "#c084fc",
    insetShadowPrimary: "#a855f7",
    insetShadowSecondary: "#e9d5ff",
  },
  {
    name: "fuchsia",
    background: "#e879f9",
    insetShadowPrimary: "#d946ef",
    insetShadowSecondary: "#f5d0fe",
  },
  {
    name: "pink",
    background: "#f472b6",
    insetShadowPrimary: "#ec4899",
    insetShadowSecondary: "#fbcfe8",
  },
  {
    name: "rose",
    background: "#fb7185",
    insetShadowPrimary: "#f43f5e",
    insetShadowSecondary: "#fecdd3",
  },
]
