export const defaultColors: Color[] = [
  {
    name: "red",
    background: "#f87171",
    insetShadowPrimary: "#ef4444",
    insetShadowSecondary: "#fca5a5",
  },
  {
    name: "orange",
    background: "#fb923c",
    insetShadowPrimary: "#f97316",
    insetShadowSecondary: "#fdba74",
  },
  {
    name: "amber",
    background: "#fbbf24",
    insetShadowPrimary: "#f59e0b",
    insetShadowSecondary: "#fcd34d",
  },
  {
    name: "yellow",
    background: "#facc15",
    insetShadowPrimary: "#eab308",
    insetShadowSecondary: "#fde047",
  },
  {
    name: "lime",
    background: "#a3e635",
    insetShadowPrimary: "#84cc16",
    insetShadowSecondary: "#bef264",
  },
  {
    name: "green",
    background: "#4ade80",
    insetShadowPrimary: "#22c55e",
    insetShadowSecondary: "#86efac",
  },
  {
    name: "emerald",
    background: "#34d399",
    insetShadowPrimary: "#10b981",
    insetShadowSecondary: "#6ee7b7",
  },
  {
    name: "teal",
    background: "#2dd4bf",
    insetShadowPrimary: "#14b8a6",
    insetShadowSecondary: "#5eead4",
  },
  {
    name: "cyan",
    background: "#22d3ee",
    insetShadowPrimary: "#06b6d4",
    insetShadowSecondary: "#cffafe",
  },
  {
    name: "sky",
    background: "#38bdf8",
    insetShadowPrimary: "#0ea5e9",
    insetShadowSecondary: "#bae6fd",
  },
  {
    name: "blue",
    background: "#60a5fa",
    insetShadowPrimary: "#3b82f6",
    insetShadowSecondary: "#bfdbfe",
  },
  {
    name: "indigo",
    background: "#818cf8",
    insetShadowPrimary: "#6366f1",
    insetShadowSecondary: "#c7d2fe",
  },
  {
    name: "violet",
    background: "#a78bfa",
    insetShadowPrimary: "#8b5cf6",
    insetShadowSecondary: "#ddd6fe",
  },
  {
    name: "purple",
    background: "#c084fc",
    insetShadowPrimary: "#a855f7",
    insetShadowSecondary: "#e9d5ff",
  },
  {
    name: "fuchsia",
    background: "#e879f9",
    insetShadowPrimary: "#d946ef",
    insetShadowSecondary: "#f5d0fe",
  },
  {
    name: "pink",
    background: "#f472b6",
    insetShadowPrimary: "#ec4899",
    insetShadowSecondary: "#fbcfe8",
  },
]
