name: Auto Release

on:
  push:
    tags:
      - "v*"

jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      - run: gh release create $GITHUB_REF_NAME --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
