name: CI

on:
  pull_request:
    branches: ["main", "develop", "release/**"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pnpm-version: [7.x.x]
        node-version: [16.x, 17.x, 18.x]

    steps:
      - uses: .github/actions/setup
        with:
          pnpm-version: ${{ matrix.pnpm-version }}
          node-version: ${{ matrix.node-version }}
      - run: pnpm run test
