name: CI

on:
  pull_request:
    branches: ["main", "develop", "release/**"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pnpm-version: [7.x.x]
        node-version: [16.x, 17.x, 18.x]

    steps:
      - uses: .github/actions/setup@e5f440e24e9b166f99cf8ad2be1f664efaaa37e4
        with:
          pnpm-version: ${{ matrix.pnpm-version }}
          node-version: ${{ matrix.node-version }}
      - run: pnpm run test
