name: Publish To NPM

on:
  release:
    types: [published]

env:
  pnpm-version: 7.x.x
  node-version: 16.x

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          pnpm-version: ${{ env.pnpm-version }}
          node-version: ${{ env.node-version }}
      - run: pnpm run build
      - run: |
          pnpm config set "//registry.npmjs.org/:_authToken" "${NPM_TOKEN}"
          pnpm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
