name: Publish To NPM

on:
  push:
    tags:
      - "v*"

env:
  pnpm-version: 7.x.x
  node-version: 16.x

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          pnpm-version: ${{ env.pnpm-version }}
          node-version: ${{ env.node-version }}
      - run: pnpm run build
      - name: publish to npm
        run: |
          pnpm config set "//registry.npmjs.org/:_authToken" "${NPM_TOKEN}"
          pnpm publish --no-git-checks
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
